### ISSUE TITLE
Issue when used with SSR?

### ISSUE THREAD

**Issue by hubert-ix** [joeattardi/svelte-emoji-selector#7]
Great component, thanks for making it available!

It works great when used with Svelte on the front end, but when I import it in Sapper it returns a server side error.
Is this something that's easily addressed?

**Comment by joeattardi** [comment]
Hi,

Thanks for checking this package out but it's been deprecated (see https://www.npmjs.com/package/svelte-emoji-selector). I should probably archive this repository.

If you are looking for an emoji picker, I'd suggest you check out my other project, Emoji Button. It's a vanilla JS emoji picker that you could probably integrate with Svelte.

https://emoji-button.js.org/
